version: "3.8"

services:
  getspot:
    image: jaturapornchai/getspot:latest
    container_name: getspot
    restart: unless-stopped
    environment:
      - OPENBLAS_NUM_THREADS=1
      - OPENBLAS_MAIN_FREE=1
      - OMP_NUM_THREADS=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
